//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InpecTurnos.ws_servicios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfficeLevel", Namespace="http://schemas.datacontract.org/2004/07/InteliTurnoServices")]
    [System.SerializableAttribute()]
    public partial class OfficeLevel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InpecTurnos.ws_servicios.ServiceLevel[] ServicesLevelsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Level {
            get {
                return this.LevelField;
            }
            set {
                if ((object.ReferenceEquals(this.LevelField, value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InpecTurnos.ws_servicios.ServiceLevel[] ServicesLevels {
            get {
                return this.ServicesLevelsField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicesLevelsField, value) != true)) {
                    this.ServicesLevelsField = value;
                    this.RaisePropertyChanged("ServicesLevels");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceLevel", Namespace="http://schemas.datacontract.org/2004/07/InteliTurnoServices")]
    [System.SerializableAttribute()]
    public partial class ServiceLevel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServicioPadreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServicioPadre {
            get {
                return this.ServicioPadreField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicioPadreField, value) != true)) {
                    this.ServicioPadreField = value;
                    this.RaisePropertyChanged("ServicioPadre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Office", Namespace="http://schemas.datacontract.org/2004/07/InteliTurnoServices")]
    [System.SerializableAttribute()]
    public partial class Office : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InpecTurnos.ws_servicios.OfficeLevel[] ServicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string latitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string longitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string scheduleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InpecTurnos.ws_servicios.OfficeLevel[] Services {
            get {
                return this.ServicesField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicesField, value) != true)) {
                    this.ServicesField = value;
                    this.RaisePropertyChanged("Services");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.latitudeField, value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.longitudeField, value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string schedule {
            get {
                return this.scheduleField;
            }
            set {
                if ((object.ReferenceEquals(this.scheduleField, value) != true)) {
                    this.scheduleField = value;
                    this.RaisePropertyChanged("schedule");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://schemas.datacontract.org/2004/07/InteliTurnoServices")]
    [System.SerializableAttribute()]
    public partial class Reservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TurnNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TurnNumber {
            get {
                return this.TurnNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TurnNumberField, value) != true)) {
                    this.TurnNumberField = value;
                    this.RaisePropertyChanged("TurnNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SqlClass", Namespace="http://schemas.datacontract.org/2004/07/InteliTurnoServices")]
    [System.SerializableAttribute()]
    public partial class SqlClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sqlInsertUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sqlInsertUser {
            get {
                return this.sqlInsertUserField;
            }
            set {
                if ((object.ReferenceEquals(this.sqlInsertUserField, value) != true)) {
                    this.sqlInsertUserField = value;
                    this.RaisePropertyChanged("sqlInsertUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TurnosSincronizar", Namespace="http://schemas.datacontract.org/2004/07/InteliTurnoServices")]
    [System.SerializableAttribute()]
    public partial class TurnosSincronizar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InpecTurnos.ws_servicios.Actividades[] ActividadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InpecTurnos.ws_servicios.OthersTurns[] abandonadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InpecTurnos.ws_servicios.ClosedTurns[] cerradosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InpecTurnos.ws_servicios.OthersTurns[] enAtencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InpecTurnos.ws_servicios.OthersTurns[] llamadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InpecTurnos.ws_servicios.Turn[] turnsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InpecTurnos.ws_servicios.Actividades[] Actividades {
            get {
                return this.ActividadesField;
            }
            set {
                if ((object.ReferenceEquals(this.ActividadesField, value) != true)) {
                    this.ActividadesField = value;
                    this.RaisePropertyChanged("Actividades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InpecTurnos.ws_servicios.OthersTurns[] abandonados {
            get {
                return this.abandonadosField;
            }
            set {
                if ((object.ReferenceEquals(this.abandonadosField, value) != true)) {
                    this.abandonadosField = value;
                    this.RaisePropertyChanged("abandonados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InpecTurnos.ws_servicios.ClosedTurns[] cerrados {
            get {
                return this.cerradosField;
            }
            set {
                if ((object.ReferenceEquals(this.cerradosField, value) != true)) {
                    this.cerradosField = value;
                    this.RaisePropertyChanged("cerrados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InpecTurnos.ws_servicios.OthersTurns[] enAtencion {
            get {
                return this.enAtencionField;
            }
            set {
                if ((object.ReferenceEquals(this.enAtencionField, value) != true)) {
                    this.enAtencionField = value;
                    this.RaisePropertyChanged("enAtencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InpecTurnos.ws_servicios.OthersTurns[] llamados {
            get {
                return this.llamadosField;
            }
            set {
                if ((object.ReferenceEquals(this.llamadosField, value) != true)) {
                    this.llamadosField = value;
                    this.RaisePropertyChanged("llamados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InpecTurnos.ws_servicios.Turn[] turns {
            get {
                return this.turnsField;
            }
            set {
                if ((object.ReferenceEquals(this.turnsField, value) != true)) {
                    this.turnsField = value;
                    this.RaisePropertyChanged("turns");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Actividades", Namespace="http://schemas.datacontract.org/2004/07/InteliTurnoServices")]
    [System.SerializableAttribute()]
    public partial class Actividades : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OfficeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReasonForSuspensionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SynchronizationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SynchronizedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OfficeId {
            get {
                return this.OfficeIdField;
            }
            set {
                if ((this.OfficeIdField.Equals(value) != true)) {
                    this.OfficeIdField = value;
                    this.RaisePropertyChanged("OfficeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReasonForSuspensionId {
            get {
                return this.ReasonForSuspensionIdField;
            }
            set {
                if ((this.ReasonForSuspensionIdField.Equals(value) != true)) {
                    this.ReasonForSuspensionIdField = value;
                    this.RaisePropertyChanged("ReasonForSuspensionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SynchronizationDate {
            get {
                return this.SynchronizationDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SynchronizationDateField, value) != true)) {
                    this.SynchronizationDateField = value;
                    this.RaisePropertyChanged("SynchronizationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Synchronized {
            get {
                return this.SynchronizedField;
            }
            set {
                if ((this.SynchronizedField.Equals(value) != true)) {
                    this.SynchronizedField = value;
                    this.RaisePropertyChanged("Synchronized");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeActivity {
            get {
                return this.TimeActivityField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeActivityField, value) != true)) {
                    this.TimeActivityField = value;
                    this.RaisePropertyChanged("TimeActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioIdField, value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OthersTurns", Namespace="http://schemas.datacontract.org/2004/07/InteliTurnoServices")]
    [System.SerializableAttribute()]
    public partial class OthersTurns : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string horaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int prioridadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int puestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int turnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hora {
            get {
                return this.horaField;
            }
            set {
                if ((object.ReferenceEquals(this.horaField, value) != true)) {
                    this.horaField = value;
                    this.RaisePropertyChanged("hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int prioridad {
            get {
                return this.prioridadField;
            }
            set {
                if ((this.prioridadField.Equals(value) != true)) {
                    this.prioridadField = value;
                    this.RaisePropertyChanged("prioridad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int puesto {
            get {
                return this.puestoField;
            }
            set {
                if ((this.puestoField.Equals(value) != true)) {
                    this.puestoField = value;
                    this.RaisePropertyChanged("puesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int turno {
            get {
                return this.turnoField;
            }
            set {
                if ((this.turnoField.Equals(value) != true)) {
                    this.turnoField = value;
                    this.RaisePropertyChanged("turno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClosedTurns", Namespace="http://schemas.datacontract.org/2004/07/InteliTurnoServices")]
    [System.SerializableAttribute()]
    public partial class ClosedTurns : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string horaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int prioridadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int puestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int turnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hora {
            get {
                return this.horaField;
            }
            set {
                if ((object.ReferenceEquals(this.horaField, value) != true)) {
                    this.horaField = value;
                    this.RaisePropertyChanged("hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.observacionesField, value) != true)) {
                    this.observacionesField = value;
                    this.RaisePropertyChanged("observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int prioridad {
            get {
                return this.prioridadField;
            }
            set {
                if ((this.prioridadField.Equals(value) != true)) {
                    this.prioridadField = value;
                    this.RaisePropertyChanged("prioridad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int puesto {
            get {
                return this.puestoField;
            }
            set {
                if ((this.puestoField.Equals(value) != true)) {
                    this.puestoField = value;
                    this.RaisePropertyChanged("puesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int turno {
            get {
                return this.turnoField;
            }
            set {
                if ((this.turnoField.Equals(value) != true)) {
                    this.turnoField = value;
                    this.RaisePropertyChanged("turno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Turn", Namespace="http://schemas.datacontract.org/2004/07/InteliTurnoServices")]
    [System.SerializableAttribute()]
    public partial class Turn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int atencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int canalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int consecutivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int desplazamientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int esperaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string generadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int oficinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int servicioTipoAtencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int atencion {
            get {
                return this.atencionField;
            }
            set {
                if ((this.atencionField.Equals(value) != true)) {
                    this.atencionField = value;
                    this.RaisePropertyChanged("atencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int canal {
            get {
                return this.canalField;
            }
            set {
                if ((this.canalField.Equals(value) != true)) {
                    this.canalField = value;
                    this.RaisePropertyChanged("canal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int consecutivo {
            get {
                return this.consecutivoField;
            }
            set {
                if ((this.consecutivoField.Equals(value) != true)) {
                    this.consecutivoField = value;
                    this.RaisePropertyChanged("consecutivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int desplazamiento {
            get {
                return this.desplazamientoField;
            }
            set {
                if ((this.desplazamientoField.Equals(value) != true)) {
                    this.desplazamientoField = value;
                    this.RaisePropertyChanged("desplazamiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int espera {
            get {
                return this.esperaField;
            }
            set {
                if ((this.esperaField.Equals(value) != true)) {
                    this.esperaField = value;
                    this.RaisePropertyChanged("espera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string generado {
            get {
                return this.generadoField;
            }
            set {
                if ((object.ReferenceEquals(this.generadoField, value) != true)) {
                    this.generadoField = value;
                    this.RaisePropertyChanged("generado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int oficina {
            get {
                return this.oficinaField;
            }
            set {
                if ((this.oficinaField.Equals(value) != true)) {
                    this.oficinaField = value;
                    this.RaisePropertyChanged("oficina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int servicioTipoAtencion {
            get {
                return this.servicioTipoAtencionField;
            }
            set {
                if ((this.servicioTipoAtencionField.Equals(value) != true)) {
                    this.servicioTipoAtencionField = value;
                    this.RaisePropertyChanged("servicioTipoAtencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                if ((object.ReferenceEquals(this.userIdField, value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TurnosSincronizados", Namespace="http://schemas.datacontract.org/2004/07/InteliTurnoServices")]
    [System.SerializableAttribute()]
    public partial class TurnosSincronizados : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ActividadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] abandonadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] cerradosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] enAtencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] llamadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] turnsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Actividades {
            get {
                return this.ActividadesField;
            }
            set {
                if ((object.ReferenceEquals(this.ActividadesField, value) != true)) {
                    this.ActividadesField = value;
                    this.RaisePropertyChanged("Actividades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] abandonados {
            get {
                return this.abandonadosField;
            }
            set {
                if ((object.ReferenceEquals(this.abandonadosField, value) != true)) {
                    this.abandonadosField = value;
                    this.RaisePropertyChanged("abandonados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] cerrados {
            get {
                return this.cerradosField;
            }
            set {
                if ((object.ReferenceEquals(this.cerradosField, value) != true)) {
                    this.cerradosField = value;
                    this.RaisePropertyChanged("cerrados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] enAtencion {
            get {
                return this.enAtencionField;
            }
            set {
                if ((object.ReferenceEquals(this.enAtencionField, value) != true)) {
                    this.enAtencionField = value;
                    this.RaisePropertyChanged("enAtencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] llamados {
            get {
                return this.llamadosField;
            }
            set {
                if ((object.ReferenceEquals(this.llamadosField, value) != true)) {
                    this.llamadosField = value;
                    this.RaisePropertyChanged("llamados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] turns {
            get {
                return this.turnsField;
            }
            set {
                if ((object.ReferenceEquals(this.turnsField, value) != true)) {
                    this.turnsField = value;
                    this.RaisePropertyChanged("turns");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EncuestasRespuestas", Namespace="http://schemas.datacontract.org/2004/07/InteliTurnoServices")]
    [System.SerializableAttribute()]
    public partial class EncuestasRespuestas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsesorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OfficeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OpcionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PreguntaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurnoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AsesorId {
            get {
                return this.AsesorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AsesorIdField, value) != true)) {
                    this.AsesorIdField = value;
                    this.RaisePropertyChanged("AsesorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OfficeId {
            get {
                return this.OfficeIdField;
            }
            set {
                if ((this.OfficeIdField.Equals(value) != true)) {
                    this.OfficeIdField = value;
                    this.RaisePropertyChanged("OfficeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OpcionId {
            get {
                return this.OpcionIdField;
            }
            set {
                if ((this.OpcionIdField.Equals(value) != true)) {
                    this.OpcionIdField = value;
                    this.RaisePropertyChanged("OpcionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PreguntaId {
            get {
                return this.PreguntaIdField;
            }
            set {
                if ((this.PreguntaIdField.Equals(value) != true)) {
                    this.PreguntaIdField = value;
                    this.RaisePropertyChanged("PreguntaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TurnoId {
            get {
                return this.TurnoIdField;
            }
            set {
                if ((this.TurnoIdField.Equals(value) != true)) {
                    this.TurnoIdField = value;
                    this.RaisePropertyChanged("TurnoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserModel", Namespace="http://schemas.datacontract.org/2004/07/InteliTurnoServices")]
    [System.SerializableAttribute()]
    public partial class UserModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPassword {
            get {
                return this.NewPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.NewPasswordField, value) != true)) {
                    this.NewPasswordField = value;
                    this.RaisePropertyChanged("NewPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ws_servicios.IOfficeServices")]
    public interface IOfficeServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/GetAllServices", ReplyAction="http://tempuri.org/IOfficeServices/GetAllServicesResponse")]
        InpecTurnos.ws_servicios.OfficeLevel[] GetAllServices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/GetAllServices", ReplyAction="http://tempuri.org/IOfficeServices/GetAllServicesResponse")]
        System.Threading.Tasks.Task<InpecTurnos.ws_servicios.OfficeLevel[]> GetAllServicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/GetAllOffices", ReplyAction="http://tempuri.org/IOfficeServices/GetAllOfficesResponse")]
        InpecTurnos.ws_servicios.Office[] GetAllOffices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/GetAllOffices", ReplyAction="http://tempuri.org/IOfficeServices/GetAllOfficesResponse")]
        System.Threading.Tasks.Task<InpecTurnos.ws_servicios.Office[]> GetAllOfficesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/QueueTurn", ReplyAction="http://tempuri.org/IOfficeServices/QueueTurnResponse")]
        InpecTurnos.ws_servicios.Reservation QueueTurn(string OfficeId, string ServiceId, string UserId, string lati, string longi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/QueueTurn", ReplyAction="http://tempuri.org/IOfficeServices/QueueTurnResponse")]
        System.Threading.Tasks.Task<InpecTurnos.ws_servicios.Reservation> QueueTurnAsync(string OfficeId, string ServiceId, string UserId, string lati, string longi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/ModifyTurn", ReplyAction="http://tempuri.org/IOfficeServices/ModifyTurnResponse")]
        InpecTurnos.ws_servicios.Reservation ModifyTurn(string OfficeId, string ReserveId, string Action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/ModifyTurn", ReplyAction="http://tempuri.org/IOfficeServices/ModifyTurnResponse")]
        System.Threading.Tasks.Task<InpecTurnos.ws_servicios.Reservation> ModifyTurnAsync(string OfficeId, string ReserveId, string Action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/UpdateTurnNumber", ReplyAction="http://tempuri.org/IOfficeServices/UpdateTurnNumberResponse")]
        string UpdateTurnNumber(string OfficeId, string ReserveId, string TurnNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/UpdateTurnNumber", ReplyAction="http://tempuri.org/IOfficeServices/UpdateTurnNumberResponse")]
        System.Threading.Tasks.Task<string> UpdateTurnNumberAsync(string OfficeId, string ReserveId, string TurnNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/QueryTurnNumber", ReplyAction="http://tempuri.org/IOfficeServices/QueryTurnNumberResponse")]
        InpecTurnos.ws_servicios.Reservation QueryTurnNumber(string OfficeId, string ReserveId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/QueryTurnNumber", ReplyAction="http://tempuri.org/IOfficeServices/QueryTurnNumberResponse")]
        System.Threading.Tasks.Task<InpecTurnos.ws_servicios.Reservation> QueryTurnNumberAsync(string OfficeId, string ReserveId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/InsertUserIdentity", ReplyAction="http://tempuri.org/IOfficeServices/InsertUserIdentityResponse")]
        string InsertUserIdentity(InpecTurnos.ws_servicios.SqlClass sqlObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/InsertUserIdentity", ReplyAction="http://tempuri.org/IOfficeServices/InsertUserIdentityResponse")]
        System.Threading.Tasks.Task<string> InsertUserIdentityAsync(InpecTurnos.ws_servicios.SqlClass sqlObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/SincronizarDatos", ReplyAction="http://tempuri.org/IOfficeServices/SincronizarDatosResponse")]
        InpecTurnos.ws_servicios.TurnosSincronizados SincronizarDatos(InpecTurnos.ws_servicios.TurnosSincronizar JSonASincronizar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/SincronizarDatos", ReplyAction="http://tempuri.org/IOfficeServices/SincronizarDatosResponse")]
        System.Threading.Tasks.Task<InpecTurnos.ws_servicios.TurnosSincronizados> SincronizarDatosAsync(InpecTurnos.ws_servicios.TurnosSincronizar JSonASincronizar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/SincronizarRespuestasEncuestas", ReplyAction="http://tempuri.org/IOfficeServices/SincronizarRespuestasEncuestasResponse")]
        string[] SincronizarRespuestasEncuestas(InpecTurnos.ws_servicios.EncuestasRespuestas[] Respuestas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/SincronizarRespuestasEncuestas", ReplyAction="http://tempuri.org/IOfficeServices/SincronizarRespuestasEncuestasResponse")]
        System.Threading.Tasks.Task<string[]> SincronizarRespuestasEncuestasAsync(InpecTurnos.ws_servicios.EncuestasRespuestas[] Respuestas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/changePassword", ReplyAction="http://tempuri.org/IOfficeServices/changePasswordResponse")]
        string changePassword(InpecTurnos.ws_servicios.UserModel User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfficeServices/changePassword", ReplyAction="http://tempuri.org/IOfficeServices/changePasswordResponse")]
        System.Threading.Tasks.Task<string> changePasswordAsync(InpecTurnos.ws_servicios.UserModel User);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOfficeServicesChannel : InpecTurnos.ws_servicios.IOfficeServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OfficeServicesClient : System.ServiceModel.ClientBase<InpecTurnos.ws_servicios.IOfficeServices>, InpecTurnos.ws_servicios.IOfficeServices {
        
        public OfficeServicesClient() {
        }
        
        public OfficeServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OfficeServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfficeServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfficeServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public InpecTurnos.ws_servicios.OfficeLevel[] GetAllServices() {
            return base.Channel.GetAllServices();
        }
        
        public System.Threading.Tasks.Task<InpecTurnos.ws_servicios.OfficeLevel[]> GetAllServicesAsync() {
            return base.Channel.GetAllServicesAsync();
        }
        
        public InpecTurnos.ws_servicios.Office[] GetAllOffices() {
            return base.Channel.GetAllOffices();
        }
        
        public System.Threading.Tasks.Task<InpecTurnos.ws_servicios.Office[]> GetAllOfficesAsync() {
            return base.Channel.GetAllOfficesAsync();
        }
        
        public InpecTurnos.ws_servicios.Reservation QueueTurn(string OfficeId, string ServiceId, string UserId, string lati, string longi) {
            return base.Channel.QueueTurn(OfficeId, ServiceId, UserId, lati, longi);
        }
        
        public System.Threading.Tasks.Task<InpecTurnos.ws_servicios.Reservation> QueueTurnAsync(string OfficeId, string ServiceId, string UserId, string lati, string longi) {
            return base.Channel.QueueTurnAsync(OfficeId, ServiceId, UserId, lati, longi);
        }
        
        public InpecTurnos.ws_servicios.Reservation ModifyTurn(string OfficeId, string ReserveId, string Action) {
            return base.Channel.ModifyTurn(OfficeId, ReserveId, Action);
        }
        
        public System.Threading.Tasks.Task<InpecTurnos.ws_servicios.Reservation> ModifyTurnAsync(string OfficeId, string ReserveId, string Action) {
            return base.Channel.ModifyTurnAsync(OfficeId, ReserveId, Action);
        }
        
        public string UpdateTurnNumber(string OfficeId, string ReserveId, string TurnNumber) {
            return base.Channel.UpdateTurnNumber(OfficeId, ReserveId, TurnNumber);
        }
        
        public System.Threading.Tasks.Task<string> UpdateTurnNumberAsync(string OfficeId, string ReserveId, string TurnNumber) {
            return base.Channel.UpdateTurnNumberAsync(OfficeId, ReserveId, TurnNumber);
        }
        
        public InpecTurnos.ws_servicios.Reservation QueryTurnNumber(string OfficeId, string ReserveId) {
            return base.Channel.QueryTurnNumber(OfficeId, ReserveId);
        }
        
        public System.Threading.Tasks.Task<InpecTurnos.ws_servicios.Reservation> QueryTurnNumberAsync(string OfficeId, string ReserveId) {
            return base.Channel.QueryTurnNumberAsync(OfficeId, ReserveId);
        }
        
        public string InsertUserIdentity(InpecTurnos.ws_servicios.SqlClass sqlObj) {
            return base.Channel.InsertUserIdentity(sqlObj);
        }
        
        public System.Threading.Tasks.Task<string> InsertUserIdentityAsync(InpecTurnos.ws_servicios.SqlClass sqlObj) {
            return base.Channel.InsertUserIdentityAsync(sqlObj);
        }
        
        public InpecTurnos.ws_servicios.TurnosSincronizados SincronizarDatos(InpecTurnos.ws_servicios.TurnosSincronizar JSonASincronizar) {
            return base.Channel.SincronizarDatos(JSonASincronizar);
        }
        
        public System.Threading.Tasks.Task<InpecTurnos.ws_servicios.TurnosSincronizados> SincronizarDatosAsync(InpecTurnos.ws_servicios.TurnosSincronizar JSonASincronizar) {
            return base.Channel.SincronizarDatosAsync(JSonASincronizar);
        }
        
        public string[] SincronizarRespuestasEncuestas(InpecTurnos.ws_servicios.EncuestasRespuestas[] Respuestas) {
            return base.Channel.SincronizarRespuestasEncuestas(Respuestas);
        }
        
        public System.Threading.Tasks.Task<string[]> SincronizarRespuestasEncuestasAsync(InpecTurnos.ws_servicios.EncuestasRespuestas[] Respuestas) {
            return base.Channel.SincronizarRespuestasEncuestasAsync(Respuestas);
        }
        
        public string changePassword(InpecTurnos.ws_servicios.UserModel User) {
            return base.Channel.changePassword(User);
        }
        
        public System.Threading.Tasks.Task<string> changePasswordAsync(InpecTurnos.ws_servicios.UserModel User) {
            return base.Channel.changePasswordAsync(User);
        }
    }
}
