//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InpecTurnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public int Id_servicio { get; set; }
        public string NombreServicio { get; set; }
    }
}
